spring.application.name=resource-booking-system

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.open-in-view=false

# JWT Configjwt.secret=8g9K2mP5xL1vR8N4qZ7wY0tC3uI6oA9sD2fG5hJ8kL1mP4qR7sT0vW3xY6zA9bC2dE5fG8hJ1kL4mP7qR0sT3vW6xY9zA2bC5dE8fG1hJ4kL7mP0qR3sT6vW9
#jwt.expirationMs=86400000